import type { Subtitle } from "./psalm23-subtitles";

/*
 * Captions for the World English Bible shorts, force-aligned to the audio.
 *
 * GENERATED by scripts/align-web-clips.py — edit that, not this.
 *
 * whisper.cpp (ggml-base.en) supplies word timings; the WORDS come from our
 * own public/bible/web text, aligned onto those timings by Needleman-Wunsch.
 * So an ASR mistake can shift a caption but can never change what it says.
 *
 * Unlike the NIV shorts these clips carry no spoken reference and no leading
 * silence — the first caption lands at t=0 and none of them needs a startAt.
 */

export const webSubtitles: Record<string, Subtitle[]> = {
  // 1peter3-v14-web.mp3 — 4 captions
  "1peter3-v14-web": [
    { id: 1, startTime: 5.13, endTime: 8.0, text: "But even if you should suffer for righteousness’ sake," },
    { id: 2, startTime: 8.0, endTime: 9.56, text: "you are blessed." },
    { id: 3, startTime: 9.56, endTime: 12.76, text: "“Don’t fear what they fear," },
    { id: 4, startTime: 12.76, endTime: 14.02, text: "neither be troubled.”" },
  ],
  // 2samuel22-v29-web.mp3 — 2 captions
  "2samuel22-v29-web": [
    { id: 1, startTime: 5.02, endTime: 8.17, text: "For you are my lamp, the LORD." },
    { id: 2, startTime: 8.17, endTime: 10.08, text: "The LORD will light up my darkness." },
  ],
  // deuteronomy31-v6-web.mp3 — 4 captions
  "deuteronomy31-v6-web": [
    { id: 1, startTime: 4.23, endTime: 6.28, text: "Be strong and courageous." },
    { id: 2, startTime: 6.28, endTime: 8.5, text: "Don’t be afraid or scared of them;" },
    { id: 3, startTime: 8.5, endTime: 12.19, text: "for the LORD your God himself is who goes with you." },
    { id: 4, startTime: 12.19, endTime: 14.86, text: "He will not fail you nor forsake you." },
  ],
  // hebrews13-v6-web.mp3 — 4 captions
  "hebrews13-v6-web": [
    { id: 1, startTime: 3.94, endTime: 6.1, text: "So that with good courage we say," },
    { id: 2, startTime: 6.1, endTime: 7.79, text: "“The Lord is my helper." },
    { id: 3, startTime: 7.79, endTime: 9.59, text: "I will not fear." },
    { id: 4, startTime: 9.59, endTime: 12.17, text: "What can man do to me?”" },
  ],
  // isaiah12-v2-web.mp3 — 6 captions
  "isaiah12-v2-web": [
    { id: 1, startTime: 2.28, endTime: 6.06, text: "Behold, God is my salvation." },
    { id: 2, startTime: 6.06, endTime: 7.01, text: "I will trust," },
    { id: 3, startTime: 7.01, endTime: 9.05, text: "and will not be afraid;" },
    { id: 4, startTime: 9.05, endTime: 9.68, text: "for Yah, the LORD," },
    { id: 5, startTime: 9.68, endTime: 11.37, text: "is my strength and song;" },
    { id: 6, startTime: 11.37, endTime: 13.98, text: "and he has become my salvation." },
  ],
  // isaiah41-v10-web.mp3 — 7 captions
  "isaiah41-v10-web": [
    { id: 1, startTime: 3.61, endTime: 4.74, text: "Don’t you be afraid," },
    { id: 2, startTime: 4.74, endTime: 6.02, text: "for I am with you." },
    { id: 3, startTime: 6.02, endTime: 7.54, text: "Don’t be dismayed," },
    { id: 4, startTime: 7.54, endTime: 8.87, text: "for I am your God." },
    { id: 5, startTime: 8.87, endTime: 11.01, text: "I will strengthen you." },
    { id: 6, startTime: 11.01, endTime: 12.77, text: "Yes, I will help you." },
    { id: 7, startTime: 12.77, endTime: 17.0, text: "Yes, I will uphold you with the right hand of my righteousness." },
  ],
  // nahum1-v7-web.mp3 — 3 captions
  "nahum1-v7-web": [
    { id: 1, startTime: 3.21, endTime: 4.56, text: "The LORD is good," },
    { id: 2, startTime: 4.56, endTime: 7.61, text: "a stronghold in the day of trouble;" },
    { id: 3, startTime: 7.61, endTime: 10.17, text: "and he knows those who take refuge in him." },
  ],
  // proverbs18-v10-web.mp3 — 3 captions
  "proverbs18-v10-web": [
    { id: 1, startTime: 3.27, endTime: 5.6, text: "The LORD’s name is a strong tower:" },
    { id: 2, startTime: 5.6, endTime: 7.31, text: "the righteous run to him," },
    { id: 3, startTime: 7.31, endTime: 8.22, text: "and are safe." },
  ],
  // psalm18-v2-web.mp3 — 6 captions
  "psalm18-v2-web": [
    { id: 1, startTime: 2.22, endTime: 3.7, text: "The LORD is my rock," },
    { id: 2, startTime: 3.7, endTime: 6.67, text: "my fortress, and my deliverer;" },
    { id: 3, startTime: 6.67, endTime: 8.14, text: "my God, my rock," },
    { id: 4, startTime: 8.14, endTime: 9.59, text: "in whom I take refuge;" },
    { id: 5, startTime: 9.59, endTime: 12.68, text: "my shield, and the horn of my salvation," },
    { id: 6, startTime: 12.68, endTime: 15.05, text: "my high tower." },
  ],
  // psalm25-v4-5-web.mp3 — 6 captions
  "psalm25-v4-5-web": [
    { id: 1, startTime: 5.27, endTime: 7.36, text: "Show me your ways, the LORD." },
    { id: 2, startTime: 7.36, endTime: 9.84, text: "Teach me your paths." },
    { id: 3, startTime: 9.84, endTime: 11.15, text: "Guide me in your truth," },
    { id: 4, startTime: 11.15, endTime: 12.66, text: "and teach me," },
    { id: 5, startTime: 12.66, endTime: 16.16, text: "For you are the God of my salvation," },
    { id: 6, startTime: 16.16, endTime: 19.27, text: "I wait for you all day long." },
  ],
  // psalm28-v7-8-web.mp3 — 7 captions
  "psalm28-v7-8-web": [
    { id: 1, startTime: 4.08, endTime: 7.64, text: "The LORD is my strength and my shield." },
    { id: 2, startTime: 7.64, endTime: 9.88, text: "My heart has trusted in him," },
    { id: 3, startTime: 9.88, endTime: 11.88, text: "and I am helped." },
    { id: 4, startTime: 11.88, endTime: 15.28, text: "Therefore my heart greatly rejoices." },
    { id: 5, startTime: 15.28, endTime: 17.96, text: "With my song I will thank him." },
    { id: 6, startTime: 17.96, endTime: 20.21, text: "The LORD is their strength." },
    { id: 7, startTime: 20.21, endTime: 23.64, text: "He is a stronghold of salvation to his anointed." },
  ],
  // psalm46-v1-2-web.mp3 — 5 captions
  "psalm46-v1-2-web": [
    { id: 1, startTime: 3.19, endTime: 5.51, text: "God is our refuge and strength," },
    { id: 2, startTime: 5.51, endTime: 7.76, text: "a very present help in trouble." },
    { id: 3, startTime: 7.76, endTime: 9.67, text: "Therefore we won’t be afraid," },
    { id: 4, startTime: 9.67, endTime: 11.36, text: "though the earth changes," },
    { id: 5, startTime: 11.36, endTime: 14.26, text: "though the mountains are shaken into the heart of the seas;" },
  ],
  // psalm61-v3-web.mp3 — 2 captions
  "psalm61-v3-web": [
    { id: 1, startTime: 3.58, endTime: 6.86, text: "For you have been a refuge for me," },
    { id: 2, startTime: 6.86, endTime: 9.01, text: "a strong tower from the enemy." },
  ],
  // psalm62-v2-6-web.mp3 — 4 captions
  "psalm62-v2-6-web": [
    { id: 1, startTime: 5.22, endTime: 8.44, text: "He alone is my rock and my salvation," },
    { id: 2, startTime: 8.44, endTime: 12.86, text: "my fortress— I will never be greatly shaken." },
    { id: 3, startTime: 12.86, endTime: 17.02, text: "He alone is my rock and my salvation, my fortress." },
    { id: 4, startTime: 17.02, endTime: 18.99, text: "I will not be shaken." },
  ],
  // romans8-v31-web.mp3 — 3 captions
  "romans8-v31-web": [
    { id: 1, startTime: 4.96, endTime: 8.06, text: "What then shall we say about these things?" },
    { id: 2, startTime: 8.06, endTime: 9.85, text: "If God is for us," },
    { id: 3, startTime: 9.85, endTime: 11.33, text: "who can be against us?" },
  ],
};
