import type { Subtitle } from "./psalm23-subtitles";

/*
 * Captions for the verse cards, force-aligned to the audio.
 *
 * GENERATED by scripts/align-web-clips.py — edit that, not this.
 *
 * whisper.cpp (ggml-base.en) supplies word timings; the WORDS come from the
 * reference text in scripts/web-clips.json, laid onto those timings by
 * Needleman-Wunsch. So an ASR mistake can shift a caption but can never
 * change what it says.
 *
 * Almost all of these are the World English Bible, taken from our own
 * public/bible/web. Isaiah 45:2 is the exception: that recording is NIV, a
 * translation we do not ship, so its wording is carried in the manifest and
 * was confirmed word for word against the transcript before use.
 */

export const webSubtitles: Record<string, Subtitle[]> = {
  // 1peter3-v14-web.mp3 — 4 captions
  "1peter3-v14-web": [
    { id: 1, startTime: 5.13, endTime: 8.0, text: "But even if you should suffer for righteousness’ sake," },
    { id: 2, startTime: 8.0, endTime: 9.56, text: "you are blessed." },
    { id: 3, startTime: 9.56, endTime: 12.76, text: "“Don’t fear what they fear," },
    { id: 4, startTime: 12.76, endTime: 14.02, text: "neither be troubled.”" },
  ],
  // 2samuel22-v29-web.mp3 — 2 captions
  "2samuel22-v29-web": [
    { id: 1, startTime: 5.02, endTime: 8.17, text: "For you are my lamp, the LORD." },
    { id: 2, startTime: 8.17, endTime: 10.08, text: "The LORD will light up my darkness." },
  ],
  // deuteronomy31-v6-web.mp3 — 4 captions
  "deuteronomy31-v6-web": [
    { id: 1, startTime: 4.23, endTime: 6.28, text: "Be strong and courageous." },
    { id: 2, startTime: 6.28, endTime: 8.5, text: "Don’t be afraid or scared of them;" },
    { id: 3, startTime: 8.5, endTime: 12.19, text: "for the LORD your God himself is who goes with you." },
    { id: 4, startTime: 12.19, endTime: 14.86, text: "He will not fail you nor forsake you." },
  ],
  // hebrews13-v6-web.mp3 — 4 captions
  "hebrews13-v6-web": [
    { id: 1, startTime: 3.94, endTime: 6.1, text: "So that with good courage we say," },
    { id: 2, startTime: 6.1, endTime: 7.79, text: "“The Lord is my helper." },
    { id: 3, startTime: 7.79, endTime: 9.59, text: "I will not fear." },
    { id: 4, startTime: 9.59, endTime: 12.17, text: "What can man do to me?”" },
  ],
  // isaiah12-v2-web.mp3 — 6 captions
  "isaiah12-v2-web": [
    { id: 1, startTime: 2.28, endTime: 6.06, text: "Behold, God is my salvation." },
    { id: 2, startTime: 6.06, endTime: 7.01, text: "I will trust," },
    { id: 3, startTime: 7.01, endTime: 9.05, text: "and will not be afraid;" },
    { id: 4, startTime: 9.05, endTime: 9.68, text: "for Yah, the LORD," },
    { id: 5, startTime: 9.68, endTime: 11.37, text: "is my strength and song;" },
    { id: 6, startTime: 11.37, endTime: 13.98, text: "and he has become my salvation." },
  ],
  // isaiah41-v10-web.mp3 — 7 captions
  "isaiah41-v10-web": [
    { id: 1, startTime: 3.61, endTime: 4.74, text: "Don’t you be afraid," },
    { id: 2, startTime: 4.74, endTime: 6.02, text: "for I am with you." },
    { id: 3, startTime: 6.02, endTime: 7.54, text: "Don’t be dismayed," },
    { id: 4, startTime: 7.54, endTime: 8.87, text: "for I am your God." },
    { id: 5, startTime: 8.87, endTime: 11.01, text: "I will strengthen you." },
    { id: 6, startTime: 11.01, endTime: 12.77, text: "Yes, I will help you." },
    { id: 7, startTime: 12.77, endTime: 17.0, text: "Yes, I will uphold you with the right hand of my righteousness." },
  ],
  // nahum1-v7-web.mp3 — 3 captions
  "nahum1-v7-web": [
    { id: 1, startTime: 3.21, endTime: 4.56, text: "The LORD is good," },
    { id: 2, startTime: 4.56, endTime: 7.61, text: "a stronghold in the day of trouble;" },
    { id: 3, startTime: 7.61, endTime: 10.17, text: "and he knows those who take refuge in him." },
  ],
  // proverbs18-v10-web.mp3 — 3 captions
  "proverbs18-v10-web": [
    { id: 1, startTime: 3.27, endTime: 5.6, text: "The LORD’s name is a strong tower:" },
    { id: 2, startTime: 5.6, endTime: 7.31, text: "the righteous run to him," },
    { id: 3, startTime: 7.31, endTime: 8.22, text: "and are safe." },
  ],
  // psalm18-v2-web.mp3 — 6 captions
  "psalm18-v2-web": [
    { id: 1, startTime: 2.22, endTime: 3.7, text: "The LORD is my rock," },
    { id: 2, startTime: 3.7, endTime: 6.67, text: "my fortress, and my deliverer;" },
    { id: 3, startTime: 6.67, endTime: 8.14, text: "my God, my rock," },
    { id: 4, startTime: 8.14, endTime: 9.59, text: "in whom I take refuge;" },
    { id: 5, startTime: 9.59, endTime: 12.68, text: "my shield, and the horn of my salvation," },
    { id: 6, startTime: 12.68, endTime: 15.05, text: "my high tower." },
  ],
  // psalm25-v4-5-web.mp3 — 6 captions
  "psalm25-v4-5-web": [
    { id: 1, startTime: 5.27, endTime: 7.36, text: "Show me your ways, the LORD." },
    { id: 2, startTime: 7.36, endTime: 9.84, text: "Teach me your paths." },
    { id: 3, startTime: 9.84, endTime: 11.15, text: "Guide me in your truth," },
    { id: 4, startTime: 11.15, endTime: 12.66, text: "and teach me," },
    { id: 5, startTime: 12.66, endTime: 16.16, text: "For you are the God of my salvation," },
    { id: 6, startTime: 16.16, endTime: 19.27, text: "I wait for you all day long." },
  ],
  // psalm28-v7-8-web.mp3 — 7 captions
  "psalm28-v7-8-web": [
    { id: 1, startTime: 4.08, endTime: 7.64, text: "The LORD is my strength and my shield." },
    { id: 2, startTime: 7.64, endTime: 9.88, text: "My heart has trusted in him," },
    { id: 3, startTime: 9.88, endTime: 11.88, text: "and I am helped." },
    { id: 4, startTime: 11.88, endTime: 15.28, text: "Therefore my heart greatly rejoices." },
    { id: 5, startTime: 15.28, endTime: 17.96, text: "With my song I will thank him." },
    { id: 6, startTime: 17.96, endTime: 20.21, text: "The LORD is their strength." },
    { id: 7, startTime: 20.21, endTime: 23.64, text: "He is a stronghold of salvation to his anointed." },
  ],
  // psalm46-v1-2-web.mp3 — 5 captions
  "psalm46-v1-2-web": [
    { id: 1, startTime: 3.19, endTime: 5.51, text: "God is our refuge and strength," },
    { id: 2, startTime: 5.51, endTime: 7.76, text: "a very present help in trouble." },
    { id: 3, startTime: 7.76, endTime: 9.67, text: "Therefore we won’t be afraid," },
    { id: 4, startTime: 9.67, endTime: 11.36, text: "though the earth changes," },
    { id: 5, startTime: 11.36, endTime: 14.26, text: "though the mountains are shaken into the heart of the seas;" },
  ],
  // psalm61-v3-web.mp3 — 2 captions
  "psalm61-v3-web": [
    { id: 1, startTime: 3.58, endTime: 6.86, text: "For you have been a refuge for me," },
    { id: 2, startTime: 6.86, endTime: 9.01, text: "a strong tower from the enemy." },
  ],
  // psalm62-v2-6-web.mp3 — 4 captions
  "psalm62-v2-6-web": [
    { id: 1, startTime: 5.22, endTime: 8.44, text: "He alone is my rock and my salvation," },
    { id: 2, startTime: 8.44, endTime: 12.86, text: "my fortress— I will never be greatly shaken." },
    { id: 3, startTime: 12.86, endTime: 17.02, text: "He alone is my rock and my salvation, my fortress." },
    { id: 4, startTime: 17.02, endTime: 18.99, text: "I will not be shaken." },
  ],
  // romans8-v31-web.mp3 — 3 captions
  "romans8-v31-web": [
    { id: 1, startTime: 4.96, endTime: 8.06, text: "What then shall we say about these things?" },
    { id: 2, startTime: 8.06, endTime: 9.85, text: "If God is for us," },
    { id: 3, startTime: 9.85, endTime: 11.33, text: "who can be against us?" },
  ],
  // isaiah45-v2.mp3 — 3 captions
  "isaiah45-v2": [
    { id: 1, startTime: 3.2, endTime: 6.53, text: "I will go before you and will level the mountains;" },
    { id: 2, startTime: 6.53, endTime: 8.82, text: "I will break down gates of bronze and" },
    { id: 3, startTime: 8.82, endTime: 10.91, text: "cut through bars of iron." },
  ],
  // psalm118-v6-7-web.mp3 — 5 captions
  "psalm118-v6-7-web": [
    { id: 1, startTime: 5.89, endTime: 8.33, text: "The LORD is on my side." },
    { id: 2, startTime: 8.33, endTime: 10.48, text: "I will not be afraid." },
    { id: 3, startTime: 10.48, endTime: 12.76, text: "What can man do to me?" },
    { id: 4, startTime: 12.76, endTime: 16.88, text: "The LORD is on my side among those who help me." },
    { id: 5, startTime: 16.88, endTime: 20.48, text: "Therefore I will look in triumph at those who hate me." },
  ],
  // psalm56-v3-4-web.mp3 — 6 captions
  "psalm56-v3-4-web": [
    { id: 1, startTime: 2.48, endTime: 5.43, text: "When I am afraid," },
    { id: 2, startTime: 5.43, endTime: 8.16, text: "I will put my trust in you." },
    { id: 3, startTime: 8.16, endTime: 11.2, text: "In God, I praise his word." },
    { id: 4, startTime: 10.48, endTime: 12.98, text: "In God, I put my trust." },
    { id: 5, startTime: 12.98, endTime: 15.44, text: "I will not be afraid." },
    { id: 6, startTime: 15.44, endTime: 18.76, text: "What can flesh do to me?" },
  ],
  // psalm121-v1-2-web.mp3 — 4 captions
  "psalm121-v1-2-web": [
    { id: 1, startTime: 4.27, endTime: 7.42, text: "I will lift up my eyes to the hills." },
    { id: 2, startTime: 7.42, endTime: 9.43, text: "Where does my help come from?" },
    { id: 3, startTime: 9.43, endTime: 11.57, text: "My help comes from the LORD," },
    { id: 4, startTime: 11.57, endTime: 13.7, text: "who made heaven and earth." },
  ],
  // psalm46-v6-7-web.mp3 — 6 captions
  "psalm46-v6-7-web": [
    { id: 1, startTime: 5.26, endTime: 6.9, text: "The nations raged." },
    { id: 2, startTime: 6.9, endTime: 8.8, text: "The kingdoms were moved." },
    { id: 3, startTime: 8.8, endTime: 10.16, text: "He lifted his voice," },
    { id: 4, startTime: 10.16, endTime: 12.85, text: "and the earth melted." },
    { id: 5, startTime: 12.85, endTime: 15.59, text: "The LORD of Armies is with us." },
    { id: 6, startTime: 15.59, endTime: 19.13, text: "The God of Jacob is our refuge. Selah." },
  ],
  // 2chronicles20-v15-web.mp3 — 8 captions
  "2chronicles20-v15-web": [
    { id: 1, startTime: 4.86, endTime: 5.64, text: "and he said," },
    { id: 2, startTime: 5.64, endTime: 7.75, text: "Listen, all Judah," },
    { id: 3, startTime: 7.75, endTime: 10.4, text: "and you inhabitants of Jerusalem," },
    { id: 4, startTime: 10.4, endTime: 13.28, text: "and you king Jehoshaphat." },
    { id: 5, startTime: 13.28, endTime: 15.0, text: "Thus says the LORD to you," },
    { id: 6, startTime: 15.0, endTime: 16.76, text: "‘Don’t be afraid," },
    { id: 7, startTime: 16.52, endTime: 19.73, text: "neither be dismayed by reason of this great multitude;" },
    { id: 8, startTime: 19.73, endTime: 22.62, text: "for the battle is not yours, but God’s." },
  ],
  // exodus14-v13-14-web.mp3 — 8 captions
  "exodus14-v13-14-web": [
    { id: 1, startTime: 3.29, endTime: 6.48, text: "Moses said to the people," },
    { id: 2, startTime: 6.48, endTime: 9.24, text: "“Don’t be afraid." },
    { id: 3, startTime: 9.24, endTime: 11.63, text: "Stand still, and see the salvation of the LORD," },
    { id: 4, startTime: 11.63, endTime: 13.5, text: "which he will work for you today:" },
    { id: 5, startTime: 13.5, endTime: 16.31, text: "for the Egyptians whom you have seen today," },
    { id: 6, startTime: 16.31, endTime: 18.56, text: "you shall never see them again." },
    { id: 7, startTime: 18.56, endTime: 20.47, text: "The LORD will fight for you," },
    { id: 8, startTime: 20.47, endTime: 22.38, text: "and you shall be still.”" },
  ],
  // psalm138-v7-web.mp3 — 5 captions
  "psalm138-v7-web": [
    { id: 1, startTime: 4.48, endTime: 6.81, text: "Though I walk in the midst of trouble," },
    { id: 2, startTime: 6.81, endTime: 8.8, text: "you will revive me." },
    { id: 3, startTime: 8.8, endTime: 10.92, text: "You will stretch out your hand against the" },
    { id: 4, startTime: 10.92, endTime: 12.21, text: "wrath of my enemies." },
    { id: 5, startTime: 12.21, endTime: 14.4, text: "Your right hand will save me." },
  ],
  // isaiah40-v30-31-web.mp3 — 8 captions
  "isaiah40-v30-31-web": [
    { id: 1, startTime: 5.3, endTime: 7.26, text: "Even the youths faint and get weary," },
    { id: 2, startTime: 7.26, endTime: 10.3, text: "and the young men utterly fall;" },
    { id: 3, startTime: 10.3, endTime: 14.19, text: "But those who wait for the LORD will renew their strength." },
    { id: 4, startTime: 14.19, endTime: 17.35, text: "They will mount up with wings like eagles." },
    { id: 5, startTime: 17.35, endTime: 18.29, text: "They will run," },
    { id: 6, startTime: 18.29, endTime: 19.8, text: "and not be weary." },
    { id: 7, startTime: 19.8, endTime: 20.94, text: "They will walk," },
    { id: 8, startTime: 20.94, endTime: 22.62, text: "and not faint." },
  ],
  // 2corinthians4-v8-9-web.mp3 — 5 captions
  "2corinthians4-v8-9-web": [
    { id: 1, startTime: 5.36, endTime: 7.16, text: "We are pressed on every side," },
    { id: 2, startTime: 7.16, endTime: 8.36, text: "yet not crushed;" },
    { id: 3, startTime: 8.36, endTime: 11.09, text: "perplexed, yet not to despair;" },
    { id: 4, startTime: 11.09, endTime: 13.47, text: "pursued, yet not forsaken;" },
    { id: 5, startTime: 13.47, endTime: 16.44, text: "struck down, yet not destroyed;" },
  ],
};
